micronaut:
  application:
    name: keyManagerRestApi

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10

  channels:
    keyManagerRestApi:
      address: ${GRPC_URL:`localhost:50051`}
      plaintext: true
      max-retry-attempts: 10